repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v6.0.0"
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
        exclude: ^src/web/
      - id: check-json
        exclude: ^(.devcontainer/devcontainer.json|src/web/)
      - id: pretty-format-json
        exclude: ^(.devcontainer/devcontainer.json|src/web/)
        args: [--autofix, --no-sort-keys]
      - id: end-of-file-fixer
        exclude: ^src/web/
      - id: trailing-whitespace
        exclude: ^src/web/

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.14.8"
    hooks:
      - id: ruff-check
        args: [ --exit-non-zero-on-fix ]
        exclude: ^src/web/
      - id: ruff-format
        exclude: ^src/web/
