name: âœ… CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  quality:
    name: ğŸ¨ Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Check out
        uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: ğŸ Set up the environment
        uses: ./.github/actions/setup-python-env

      - name: âœ¨ Run checks
        run: make check

  tests-and-type-check:
    name: ğŸ§ª Tests & Type Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.14"]
      fail-fast: false
    defaults:
      run:
        shell: bash
    steps:
      - name: ğŸ“¥ Check out
        uses: actions/checkout@v4

      - name: ğŸ Set up the environment
        uses: ./.github/actions/setup-python-env
        with:
          python-version: ${{ matrix.python-version }}

      - name: ğŸ§ª Run tests
        run: uv run python -m pytest tests --cov --cov-config=pyproject.toml --cov-report=xml

      - name: ğŸ” Check typing
        run: uv run ty check


      - name: ğŸ“Š Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  check-docs:
    name: ğŸ“š Documentation
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Check out
        uses: actions/checkout@v4

      - name: ğŸ Set up the environment
        uses: ./.github/actions/setup-python-env

      - name: ğŸ“– Check if documentation can be built
        run: uv run mkdocs build -s
